# Python List and List Operations
friends = ["Delowar","Mitu","Joty"]
print(friends)
print(type(friends))
print(friends[2])
friends.append("Mijdur")
friends.append("Yafta")
print(friends)
friends.remove("Delowar")
print(friends)
friends.pop()
print(friends)
friends.insert(2,"Delowar.Designer")
print(friends)
print(friends[0:2])
friends.sort()
print(friends)
friends.clear()
print(friends)