# Built-in tuple functions any
tuple = (1,2,3,4,5,6,7,8)
print(any(tuple))
tuple = (0,False)
print(any(tuple))
tuple = (1,3,4,0)
print(any(tuple))
tuple = (0, False, 5)
print(any(tuple))
tuple = ()
print(any(tuple))